project_id = "jttvujmznirmwdtvmyom"

[functions.generate-quote]
verify_jwt = true

[functions.send-quote-email]
verify_jwt = true

[functions.process-quote-signature]
verify_jwt = false

[functions.check-pending-quotes]
verify_jwt = false